---
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - python3
dist: trusty
sudo: false
node_js:
  - "6.3"
branches:
  only:
    - master
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
before_script:
  - git clone https://github.com/DMTF/Redfish-Tools.git /tmp/Redfish-Tools
script:
  - npm test
  - python3 /tmp/Redfish-Tools/odata-csdl-validator/odata_validator.py Test_Schema.xml
after_script:
  - rm -rf /tmp/Redfish-Tools