---
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
sudo: required
node_js:
  - "6.3"
branches:
  only:
    - master
cache:
  bundler: true
  directories:
  - node_modules # NPM packages
before_install:
  - sudo apt-get -qq update
  #- sudo apt-get install -y python3.5
before_script:
  - git clone https://github.com/DMTF/Redfish-Tools.git /tmp/Redfish-Tools
script:
  - npm test
  - which python
  - which python3
  - which python3.5
  - python -V
  - python3 -V
  - python3.5 -V
  - ls /usr/bin
  - python3.5 /tmp/Redfish-Tools/odata-csdl-validator/odata_validator.py 
after_script:
  - rm -rf /tmp/Redfish-Tools